inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

# Put development dependencies in the gemspec so rubygems.org knows about them
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

# Spaces in strings with line continuations go at the beginning of the line.
Layout/LineContinuationLeadingSpace:
  EnforcedStyle: leading

# Be lenient with line length
Layout/LineLength:
  Max: 110

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Assume the programmer knows precendence rules
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'  # Blocks can be any length in spec files
    - '*.gemspec'  # Gem spec blocks can be any size

# TODO: Update code so these maxima can be lowered
Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 4

Naming/PredicateName:
  AllowedMethods:
    - 'has_one'
    - 'has_many'
    - 'has_xml_content'

RSpec/FilePath:
  CustomTransform:
    HappyMapper: 'happymapper'

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  EnforcedStyle: comparison
